version: "3"
services:
  votenet_dev:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${USER}
    container_name: votenet_dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true

    volumes:
       - ./votenet:/home/${USER}/votenet
