version: "3"
services:
  votenet_dev:
    build: 
      context: .
      dockerfile: ./Dockerfile
#      args:
#        BUILD_USER: ${USER}
    image: votenet_dev_image
    container_name: votenet_dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    volumes:
       - ./votenet:/home/appuser/votenet
    environment:
      - LOCAL_UID=${UID}
      - LOCAL_GID=${GID}
    env_file: .env
#    entrypoint: /usr/local/bin/entrypoint.sh
#    command: /bin/bash -c "/usr/local/bin/entrypoint.sh"
